spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
